"""Added role column to User model

Revision ID: 246aa1c53d07
Revises: c53ee142d668
Create Date: 2024-10-13 12:22:48.486060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '246aa1c53d07'
down_revision = 'c53ee142d668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
